/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Où l'on est, et sur quel dépôt */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Le serveur répond-il */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lancer un job
         * @description Accepte le job et rend son identifiant : le travail part dans un fil.
         *
         *     202 et non 201 : rien n'est encore produit. Ce que la réponse garantit, c'est
         *     qu'un job existe, qu'il porte cet identifiant, et qu'il est suivable.
         */
        post: operations["submit_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** État d'un job et son manifeste */
        get: operations["detail_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Arrêter un job en cours
         * @description Arrête un job et rend son état. Le même geste que `{"op":"cancel"}` en duplex.
         *
         *     Il existe en HTTP parce qu'un bouton « stop » n'a pas besoin d'une socket :
         *     l'écran suit déjà le job par son flux d'événements, et lui demander d'en
         *     ouvrir une seconde pour un seul message coûterait plus que le message.
         *
         *     **L'arrêt tue le worker** — voir `JobRegistry.cancel`. Le job rend donc
         *     `failed`, avec `cancelled` à vrai et le texte déjà produit dans
         *     `stream_text` : c'est ce qui distingue un arrêt demandé d'une panne, et
         *     l'écran doit les présenter différemment.
         */
        post: operations["cancel_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suivre un job en direct (SSE)
         * @description Flux d'événements : un `job` à chaque changement, puis un `end`.
         *
         *     Chaque événement porte l'état complet plutôt qu'un fragment : le client
         *     remplace ce qu'il affiche, et un événement perdu ne le laisse pas dans un
         *     état composé de moitiés.
         */
        get: operations["events_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/files/{chemin}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Un fichier produit par un job
         * @description Sert un fichier du dossier du job — sorties, entrées copiées, manifeste.
         *
         *     `{chemin:path}` et non un simple nom : une séparation audio produit
         *     `tracks/vocals.wav`, et un client qui devrait recomposer ce chemin depuis une
         *     clé pointée referait le travail que `files` lui donne déjà fait.
         *
         *     Tout ce qui sort du dossier est un 404 et non un 403 : la question « ce
         *     fichier existe-t-il ailleurs sur cette machine » n'a pas à recevoir de
         *     réponse, fût-elle négative.
         */
        get: operations["fichier_jobs__job_id__files__chemin__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registry/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contrats de capacité
         * @description Les contrats, avec ce que le parc en fait aujourd'hui.
         *
         *     C'est la source du formulaire de l'Atelier : `input` est rendu tel quel par
         *     RJSF, `output_media_types` choisit le visualiseur. `ready_variants` évite le
         *     piège d'un écran qui propose une capacité déclarée mais dont aucun variant
         *     n'est téléchargé.
         */
        get: operations["capabilities_registry_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registry/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Manifestes du parc */
        get: operations["models_registry_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime/admission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ce que coûterait ce job
         * @description Chiffre un job envisagé : pic attendu, évictions, marge — sans rien charger.
         *
         *     C'est une lecture malgré le verbe : rien n'est écrit, rien n'est chargé, et
         *     deux appels identiques donnent la même réponse. `POST` parce que la question
         *     porte une entrée complète, que l'on n'écrit pas dans une chaîne de requête.
         */
        post: operations["admission_runtime_admission_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime/residents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Modèles résidents et budget */
        get: operations["residents_runtime_residents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plan de récupération, à blanc
         * @description Ce que `ecurie store plan` proposerait, sans écrire le fichier qu'il écrit.
         *
         *     Le plan rendu est **complet** — actions, empreintes, écartés — et non un
         *     résumé : c'est le document qu'on relit avant de laisser un outil toucher
         *     trente giga-octets, et un écran qui n'en montrerait que le total demanderait
         *     de faire confiance sans donner de quoi juger.
         *
         *     Il porte un `plan_id` neuf à chaque appel, comme n'importe quelle génération.
         *     Rien ne le rend rejouable pour autant : `apply` re-vérifie chaque fichier sur
         *     le disque au moment d'agir, et refuse tout ce qui a bougé depuis le scan.
         */
        get: operations["plan_store_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Occupation du parc */
        get: operations["summary_store_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/tiering": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Volumes, variants déportés, poids
         * @description Où l'on peut déporter, ce qui l'est déjà, et ce qui pèserait le plus lourd.
         *
         *     Les volumes viennent de la **configuration** et non du disque observé : un
         *     volume déclaré mais démonté doit apparaître, justement parce qu'il est
         *     démonté — c'est ce qui explique qu'un variant froid soit indisponible. Sa
         *     place libre est alors `null`, et non zéro.
         */
        get: operations["tiering_store_tiering_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Déposer un fichier et obtenir son chemin local
         * @description Écrit le fichier dans le sas et rend le chemin à poser dans le champ.
         *
         *     Le type de média vient du client quand il l'annonce, sinon de l'extension du
         *     nom : `MediaRecorder` déclare toujours le sien, un glisser-déposer depuis le
         *     Finder pas toujours. Il est ensuite confronté à ce que les contrats du
         *     registre acceptent — c'est le registre qui décide, pas une liste écrite dans
         *     ce fichier.
         */
        post: operations["deposer_fichier_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdmissionOut */
        AdmissionOut: {
            /** Admitted */
            admitted: boolean;
            /**
             * Already Resident
             * @default false
             */
            already_resident: boolean;
            /** Blockers */
            blockers?: string[];
            /** Evict */
            evict?: string[];
            /**
             * Headroom Bytes
             * @default 0
             */
            headroom_bytes: number;
            /**
             * Measure Mode
             * @default false
             */
            measure_mode: boolean;
            /**
             * Overcommit
             * @description Le job a été admis au-delà du budget, sur demande explicite. Le parc est vidé et la machine pagine : c'est un arbitrage assumé, pas un calcul qui a débordé.
             * @default false
             */
            overcommit: boolean;
            /**
             * Overflow Bytes
             * @description Ce qui dépasse le budget. Renseigné même quand le dépassement fait refuser.
             * @default 0
             */
            overflow_bytes: number;
            /**
             * Peak Bytes
             * @description Pic attendu pour cette entrée, pas seulement pour ce variant.
             */
            peak_bytes?: number | null;
            /**
             * Peak Note
             * @description Dit quand le pic est extrapolé hors de l'intervalle mesuré.
             */
            peak_note?: string | null;
            /** Reason */
            reason: string;
            /** Ref */
            ref: string;
        };
        /** AdmissionRequest */
        AdmissionRequest: {
            /**
             * Input
             * @description Entrée envisagée, déjà typée. Elle sert au pic attendu quand le profil déclare une pente : trente secondes de musique coûtent le double de quinze.
             */
            input?: {
                [key: string]: unknown;
            };
            /**
             * Overcommit
             * @description Simuler en assumant le dépassement du budget. Le bandeau s'en sert pour montrer ce que coûterait le mode hors budget avant qu'on l'ait choisi.
             * @default false
             */
            overcommit: boolean;
            /**
             * Ref
             * @description « model@variant », ou « model » quand le choix est évident.
             */
            ref: string;
            /** Seed */
            seed?: number | null;
        };
        /** AdmissionResponse */
        AdmissionResponse: {
            admission: components["schemas"]["AdmissionOut"];
            /** Blockers */
            blockers?: string[];
            /**
             * Input
             * @description Entrée complète, défauts du contrat et du variant résolus.
             */
            input?: {
                [key: string]: unknown;
            };
            /**
             * Input Errors
             * @description Ce que le contrat reproche à l'entrée. Non vide, aucun job ne partirait.
             */
            input_errors?: string[];
            /** Ready */
            ready: boolean;
            /** Ref */
            ref: string;
        };
        /** Body_deposer_fichier_uploads_post */
        Body_deposer_fichier_uploads_post: {
            /** File */
            file: string;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /** Capabilities */
            capabilities: components["schemas"]["CapabilityOut"][];
            /** Issues */
            issues?: components["schemas"]["IssueOut"][];
        };
        /** CapabilityOut */
        CapabilityOut: {
            /**
             * Composite
             * @default false
             */
            composite: boolean;
            /**
             * Defaults
             * @description Valeurs par défaut déclarées par le contrat.
             */
            defaults?: {
                [key: string]: unknown;
            };
            /** Description */
            description?: string | null;
            /**
             * Human Subject
             * @description Ce que la capacité fait d'une personne réelle, quand elle en fait quelque chose : `analyzes` la mesure sans la nommer, `identifies` la désigne, `synthesizes` produit son image ou sa voix. Absent pour la grande majorité des capacités. Distinct de `license_class`, qui dit ce que le droit interdit : un modèle parfaitement permissif peut servir à identifier quelqu'un qui n'a rien demandé.
             */
            human_subject?: string | null;
            /** Id */
            id: string;
            /**
             * Incumbent
             * @description Titulaire de la capacité, référence de toute confrontation A/B.
             */
            incumbent?: string | null;
            /**
             * Input
             * @description JSON Schema du formulaire. L'UI le rend tel quel.
             */
            input: {
                [key: string]: unknown;
            };
            /**
             * Models
             * @description Modèles du registre qui remplissent cette capacité.
             */
            models?: string[];
            /**
             * Output
             * @description JSON Schema de la sortie.
             */
            output: {
                [key: string]: unknown;
            };
            /**
             * Output Media Types
             * @description Sorties qui sont des fichiers → type de média, qui choisit le visualiseur.
             */
            output_media_types?: {
                [key: string]: string;
            };
            /**
             * Ready Variants
             * @description Variants exécutables en l'état. Vide avec des modèles présents veut dire que la capacité est déclarée mais pas encore utilisable.
             */
            ready_variants?: string[];
            /** Required */
            required?: string[];
            /** Steps */
            steps?: {
                [key: string]: unknown;
            }[];
            /** Title */
            title: string;
        };
        /** ColdLinkOut */
        ColdLinkOut: {
            /**
             * Available
             * @description La cible du lien est atteignable — volume monté.
             */
            available: boolean;
            /** Path */
            path: string;
            /** Target */
            target: string;
            /** Variant Ref */
            variant_ref?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IssueOut */
        IssueOut: {
            /** File */
            file: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning";
        };
        /** JobDetail */
        JobDetail: {
            /**
             * Cancelled
             * @description Le job a été arrêté à la demande. Il rend alors `failed` — l'arrêt passe par la mort du worker —, mais l'échec n'en est pas un, et `stream_text` garde ce qui avait déjà été produit.
             * @default false
             */
            cancelled: boolean;
            /** Capability */
            capability: string;
            /** Error */
            error?: string | null;
            /**
             * Evicted
             * @description Ce qu'il a fallu décharger pour faire de la place.
             */
            evicted?: string[];
            /**
             * Files
             * @description Sortie du contrat → URL à télécharger. Composée par le serveur : une sortie imbriquée est un chemin à plusieurs segments, que le client n'a pas à savoir.
             */
            files?: {
                [key: string]: string;
            };
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /**
             * Input
             * @description Entrée complète, défauts résolus.
             */
            input?: {
                [key: string]: unknown;
            };
            /**
             * Manifest
             * @description Manifeste du job — révision épinglée, paramètres complets, empreinte de l'entrée, versions, métriques. C'est le contrat de reproductibilité du §6, écrit dans le dossier du job. `null` tant que le job n'est pas terminé.
             */
            manifest?: {
                [key: string]: unknown;
            } | null;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
            /** Model */
            model: string;
            /**
             * Note
             * @description Ce qui se passe maintenant, en clair.
             * @default
             */
            note: string;
            /**
             * Output
             * @description Ce que le worker a rendu, tel quel. `outputs` n'en retient que les fichiers ; il faut aussi ce qui n'en est pas — une langue détectée, un nombre de pages, une liste d'appels d'outils. Le client aplatit cette réponse-là, et non les `properties` du contrat : `audio-separation` déclare cinq pistes et n'en produit que deux ou quatre.
             */
            output?: {
                [key: string]: unknown;
            };
            /**
             * Outputs
             * @description Sortie du contrat → chemin du fichier dans le dossier du job.
             */
            outputs?: {
                [key: string]: string;
            };
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Ref */
            ref: string;
            /**
             * Reused
             * @description Le modèle était déjà chaud : le warmup n'a pas été repayé.
             * @default false
             */
            reused: boolean;
            /** Seed */
            seed?: number | null;
            /** Started At */
            started_at?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "done" | "failed";
            /**
             * Stream Reasoning
             * @description Le raisonnement à voix haute, séparé de la réponse à la source. Vide pour les modèles qui n'en produisent pas, ou dont le variant l'a coupé.
             * @default
             */
            stream_reasoning: string;
            /**
             * Stream Text
             * @description La réponse telle qu'elle s'est écrite, cumulée depuis les `delta`. Ce n'est pas le résultat — `output` et les fichiers du job restent seuls à faire foi. Elle est ici pour qu'un client arrivé en cours de route n'ait pas manqué le début, et parce qu'un job annulé n'a que cela à montrer.
             * @default
             */
            stream_text: string;
            /** Submitted At */
            submitted_at: string;
            /** Variant */
            variant: string;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * JobOut
         * @description L'état d'un job, tel que le flux d'événements le répète.
         *
         *     Le même objet sert la lecture et chaque événement : le client remplace son
         *     état au lieu de recomposer des fragments, et deux chemins ne peuvent pas
         *     diverger.
         */
        JobOut: {
            /**
             * Cancelled
             * @description Le job a été arrêté à la demande. Il rend alors `failed` — l'arrêt passe par la mort du worker —, mais l'échec n'en est pas un, et `stream_text` garde ce qui avait déjà été produit.
             * @default false
             */
            cancelled: boolean;
            /** Capability */
            capability: string;
            /** Error */
            error?: string | null;
            /**
             * Evicted
             * @description Ce qu'il a fallu décharger pour faire de la place.
             */
            evicted?: string[];
            /**
             * Files
             * @description Sortie du contrat → URL à télécharger. Composée par le serveur : une sortie imbriquée est un chemin à plusieurs segments, que le client n'a pas à savoir.
             */
            files?: {
                [key: string]: string;
            };
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /**
             * Input
             * @description Entrée complète, défauts résolus.
             */
            input?: {
                [key: string]: unknown;
            };
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
            /** Model */
            model: string;
            /**
             * Note
             * @description Ce qui se passe maintenant, en clair.
             * @default
             */
            note: string;
            /**
             * Output
             * @description Ce que le worker a rendu, tel quel. `outputs` n'en retient que les fichiers ; il faut aussi ce qui n'en est pas — une langue détectée, un nombre de pages, une liste d'appels d'outils. Le client aplatit cette réponse-là, et non les `properties` du contrat : `audio-separation` déclare cinq pistes et n'en produit que deux ou quatre.
             */
            output?: {
                [key: string]: unknown;
            };
            /**
             * Outputs
             * @description Sortie du contrat → chemin du fichier dans le dossier du job.
             */
            outputs?: {
                [key: string]: string;
            };
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Ref */
            ref: string;
            /**
             * Reused
             * @description Le modèle était déjà chaud : le warmup n'a pas été repayé.
             * @default false
             */
            reused: boolean;
            /** Seed */
            seed?: number | null;
            /** Started At */
            started_at?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "done" | "failed";
            /**
             * Stream Reasoning
             * @description Le raisonnement à voix haute, séparé de la réponse à la source. Vide pour les modèles qui n'en produisent pas, ou dont le variant l'a coupé.
             * @default
             */
            stream_reasoning: string;
            /**
             * Stream Text
             * @description La réponse telle qu'elle s'est écrite, cumulée depuis les `delta`. Ce n'est pas le résultat — `output` et les fichiers du job restent seuls à faire foi. Elle est ici pour qu'un client arrivé en cours de route n'ait pas manqué le début, et parce qu'un job annulé n'a que cela à montrer.
             * @default
             */
            stream_text: string;
            /** Submitted At */
            submitted_at: string;
            /** Variant */
            variant: string;
            /** Warnings */
            warnings?: string[];
        };
        /** JobRequest */
        JobRequest: {
            /**
             * Input
             * @description Entrée du job, déjà typée — un nombre pour un nombre. Les défauts du contrat et du variant sont résolus par le serveur, et écrits au manifeste.
             */
            input?: {
                [key: string]: unknown;
            };
            /**
             * Overcommit
             * @description Assumer un dépassement du budget mémoire plutôt que de refuser le job. Vide le parc, laisse macOS paginer, et n'offre aucune garantie que le job aille au bout. Sans effet sur un modèle qui tient dans le budget.
             * @default false
             */
            overcommit: boolean;
            /**
             * Ref
             * @description « model@variant », ou « model » quand le choix est évident.
             */
            ref: string;
            /** Seed */
            seed?: number | null;
        };
        /** LinksOut */
        LinksOut: {
            /** Code */
            code?: string | null;
            /** Homepage */
            homepage?: string | null;
            /** Paper */
            paper?: string | null;
        };
        /** ModelOut */
        ModelOut: {
            /** Capability */
            capability: string;
            /** Family */
            family?: string | null;
            /** Id */
            id: string;
            /** Incumbent */
            incumbent: boolean;
            /** License */
            license: string;
            /** License Class */
            license_class?: string | null;
            links?: components["schemas"]["LinksOut"] | null;
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
            /** Status */
            status: string;
            /** Variants */
            variants: components["schemas"]["VariantOut"][];
            /** Vendor */
            vendor?: string | null;
        };
        /** ModelsResponse */
        ModelsResponse: {
            /**
             * Issues
             * @description Constats du chargement du registre. Un manifeste invalide n'est pas servi.
             */
            issues?: components["schemas"]["IssueOut"][];
            /** Models */
            models: components["schemas"]["ModelOut"][];
        };
        /** PeakScalingOut */
        PeakScalingOut: {
            /** Base Bytes */
            base_bytes: number;
            /** Bytes Per Unit */
            bytes_per_unit: number;
            /** Measured Range */
            measured_range: number[];
            /** Parameter */
            parameter: string;
            /** R Squared */
            r_squared?: number | null;
        };
        /** PolicyOut */
        PolicyOut: {
            /** Budget Bytes */
            budget_bytes: number;
            /** Heavy Threshold Bytes */
            heavy_threshold_bytes: number;
            /** Max Heavy Resident */
            max_heavy_resident: number;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Disk Bytes */
            disk_bytes: number;
            /** Harness Version */
            harness_version?: string | null;
            /** Latency Ms P50 */
            latency_ms_p50?: number | null;
            /**
             * Measured At
             * Format: date
             */
            measured_at: string;
            /** Measured On */
            measured_on: string;
            peak_scaling?: components["schemas"]["PeakScalingOut"] | null;
            /** Peak Unified Memory Bytes */
            peak_unified_memory_bytes: number;
            /** Rtf */
            rtf?: number | null;
            /** Throughput */
            throughput?: string | null;
            /** Warmup Ms */
            warmup_ms?: number | null;
        };
        /** ResidentOut */
        ResidentOut: {
            /** Busy */
            busy: boolean;
            /** Busy By */
            busy_by: number;
            /** Busy Since */
            busy_since: number;
            /** Env */
            env: string;
            /** Heavy */
            heavy: boolean;
            /** Last Used */
            last_used: number;
            /** Loaded At */
            loaded_at: string;
            /** Log */
            log: string;
            /**
             * Options
             * @description Ce que le worker a annoncé au chargement — voix, langues, versions.
             */
            options?: {
                [key: string]: unknown;
            };
            /** Peak Bytes */
            peak_bytes: number;
            /** Pid */
            pid: number;
            /** Pinned */
            pinned: boolean;
            /** Ref */
            ref: string;
            /** Runtime */
            runtime: string;
            /** Socket */
            socket: string;
            /** Warmup Ms */
            warmup_ms: number;
        };
        /** ResidentsResponse */
        ResidentsResponse: {
            admission?: components["schemas"]["AdmissionOut"] | null;
            /** Budget Bytes */
            budget_bytes: number;
            /**
             * Budget Measured
             * @description Le budget vient de Metal, et non d'une règle de trois sur la mémoire physique.
             */
            budget_measured: boolean;
            /** Budget Source */
            budget_source: string;
            /** Free Bytes */
            free_bytes: number;
            policy: components["schemas"]["PolicyOut"];
            /** Residents */
            residents: components["schemas"]["ResidentOut"][];
            /** Stale */
            stale?: components["schemas"]["StaleWorkerOut"][];
            /** Used Bytes */
            used_bytes: number;
        };
        /** SourceOut */
        SourceOut: {
            /** Allow Patterns */
            allow_patterns?: string[] | null;
            /** Kind */
            kind: string;
            /** Path */
            path?: string | null;
            /** Repo */
            repo?: string | null;
            /** Revision */
            revision?: string | null;
            /** Url */
            url?: string | null;
        };
        /**
         * StaleWorkerOut
         * @description Une entrée du registre des résidents qui ne correspond plus à un worker joignable.
         *
         *     Distinguer les deux cas est ce qui compte : un processus mort ne laisse
         *     qu'une ligne à balayer, un processus vivant dont le socket a disparu retient
         *     toujours ses gigaoctets et n'est plus comptable dans le budget.
         */
        StaleWorkerOut: {
            /** Holds Memory */
            holds_memory: boolean;
            /** Pid */
            pid: number;
            /** Ref */
            ref: string;
            /** Socket */
            socket: string;
        };
        /**
         * StorePlanResponse
         * @description Le plan de récupération, **jamais écrit** — c'est toute la différence avec la CLI.
         *
         *     `ecurie store plan` produit un fichier, parce que `ecurie store apply` en
         *     exige un : le plan est le document qu'on relit avant de laisser un outil
         *     toucher trente giga-octets. Un `GET` ne fabrique pas de document ; il montre
         *     ce qu'un plan dirait, et laisse la commande à taper pour l'obtenir pour de
         *     bon. `command` porte cette commande, parce que l'écran qui affiche un gain de
         *     quatre giga-octets doit dire par où on le prend.
         */
        StorePlanResponse: {
            /**
             * Command
             * @description La commande qui écrit ce plan et permet de l'appliquer.
             */
            command?: string | null;
            /** Hint */
            hint?: string | null;
            /**
             * Labels
             * @description Le libellé français de chaque motif d'action, tel que la CLI l'affiche — le front n'entretient pas sa propre table.
             */
            labels?: {
                [key: string]: string;
            };
            /** Last Scan At */
            last_scan_at?: string | null;
            /**
             * Plan
             * @description Le plan tel que `ecurie_store.plan.generate_plan` le produit (CONCEPTION.md §4.3), ou `null` tant qu'aucun scan n'a eu lieu.
             */
            plan?: {
                [key: string]: unknown;
            } | null;
            /** Scanned */
            scanned: boolean;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
        };
        /** StoreSummaryResponse */
        StoreSummaryResponse: {
            /**
             * Figures
             * @description Les trois chiffres et leur détail, tels que `ecurie_store.figures` les calcule. `null` — et non zéro — tant qu'aucun scan n'a eu lieu : un parc jamais regardé n'est pas un parc vide.
             */
            figures?: {
                [key: string]: unknown;
            } | null;
            /**
             * Hint
             * @description Ce qu'il faut faire quand la réponse est incomplète.
             */
            hint?: string | null;
            /** Last Scan At */
            last_scan_at?: string | null;
            /** Scanned */
            scanned: boolean;
            /**
             * Stale
             * @description Un plan a été appliqué depuis le dernier scan : ces chiffres sont périmés.
             * @default false
             */
            stale: boolean;
            telemetry?: components["schemas"]["TelemetryOut"] | null;
        };
        /** TelemetryOut */
        TelemetryOut: {
            /**
             * Conclusive
             * @description La télémétrie observe-t-elle depuis assez longtemps pour conclure ?
             */
            conclusive: boolean;
            /** First Run At */
            first_run_at?: string | null;
            /** Unused After Days */
            unused_after_days: number;
        };
        /**
         * TierVolumeOut
         * @description Un volume de `tier_volumes`, et son état au moment de la requête.
         */
        TierVolumeOut: {
            /**
             * Free Bytes
             * @description `null` quand le volume est démonté — inconnu, pas zéro.
             */
            free_bytes?: number | null;
            /**
             * Mounted
             * @description Le point de montage existe et est un dossier.
             */
            mounted: boolean;
            /** Path */
            path: string;
            /** Total Bytes */
            total_bytes?: number | null;
        };
        /**
         * TieringResponse
         * @description Ce que le tiering donne à voir : où déporter, ce qui l'est déjà, ce qui pèse.
         *
         *     Une lecture, et rien d'autre. Déporter copie des giga-octets et met des
         *     originaux en quarantaine : `ecurie store tier` le fait, avec une
         *     confirmation, et l'écran donne la commande. Un bouton qui déclencherait cela
         *     depuis un navigateur mettrait une opération irréversible à un clic d'un
         *     survol de souris.
         */
        TieringResponse: {
            /** Cold */
            cold?: components["schemas"]["ColdLinkOut"][];
            /** Hint */
            hint?: string | null;
            /** Last Scan At */
            last_scan_at?: string | null;
            /** Scanned */
            scanned: boolean;
            /** Variants */
            variants?: components["schemas"]["VariantFootprintOut"][];
            /** Volumes */
            volumes?: components["schemas"]["TierVolumeOut"][];
        };
        /**
         * UploadOut
         * @description Ce qu'un dépôt devient : un chemin, que le champ fichier du formulaire porte.
         *
         *     `path` est absolu et local à la machine du serveur. C'est délibérément la
         *     même valeur qu'on saisirait à la main dans le champ, et la même que la CLI
         *     attend (`ecurie run -p image=…`) : le dépôt fabrique un chemin, il n'invente
         *     pas une seconde façon de désigner une entrée.
         */
        UploadOut: {
            /** Media Type */
            media_type: string;
            /**
             * Name
             * @description Nom sur le disque : jeton horodaté et nom d'origine assaini.
             */
            name: string;
            /**
             * Path
             * @description Chemin absolu du fichier écrit, à poser dans le champ.
             */
            path: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VariantFootprintOut */
        VariantFootprintOut: {
            /** Bytes */
            bytes: number;
            /** Devices */
            devices?: number[];
            /** Files */
            files: number;
            /**
             * Freed Bytes
             * @description Ce que le volume de départ rendrait vraiment : un inode dont une référence échappe au parc scanné ne libère rien.
             */
            freed_bytes: number;
            /** Ref */
            ref: string;
            /** Shared With */
            shared_with?: string[];
            /** Tierable */
            tierable: boolean;
            /**
             * Tiered Links
             * @default 0
             */
            tiered_links: number;
        };
        /** VariantOut */
        VariantOut: {
            /**
             * Blockers
             * @description Ce qui manque, chaque cause portant la commande qui la répare.
             */
            blockers?: string[];
            /** Caveats */
            caveats?: string[] | null;
            /** Defaults */
            defaults?: {
                [key: string]: unknown;
            } | null;
            /** Entrypoint */
            entrypoint?: string | null;
            /**
             * Env
             * @description Environnement isolé sous runtimes/, runtime par défaut.
             */
            env: string;
            /**
             * Heavy
             * @description Pic au-dessus de heavy_threshold_bytes : ce variant ne cohabitera avec aucun autre lourd. Inconnu sans profil mesuré.
             */
            heavy?: boolean | null;
            /** Id */
            id: string;
            /** Options */
            options?: {
                [key: string]: unknown;
            } | null;
            profile?: components["schemas"]["ProfileOut"] | null;
            /** Quantization */
            quantization?: string | null;
            /**
             * Ready
             * @description Exécutable en l'état : poids, environnement et profil.
             */
            ready: boolean;
            /**
             * Ref
             * @description « model@variant » — l'identifiant qu'attendent run et bench.
             */
            ref: string;
            /** Runtime */
            runtime: string;
            source: components["schemas"]["SourceOut"];
            /**
             * Tier
             * @description Présence déclarée au manifeste : hot, cold ou absent.
             */
            tier: string;
            /**
             * Weights Path
             * @description Chemin local des poids, quand ils sont là.
             */
            weights_path?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    submit_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fichier_jobs__job_id__files__chemin__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                chemin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_registry_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    models_registry_models_get: {
        parameters: {
            query?: {
                /** @description Ne rendre que les modèles de cette capacité. */
                capability?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admission_runtime_admission_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdmissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdmissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    residents_runtime_residents_get: {
        parameters: {
            query?: {
                /** @description Simuler l'admission de ce variant, sans rien charger ni décharger. */
                for?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_store_plan_get: {
        parameters: {
            query?: {
                unused_after_days?: number;
                /** @description Ne dédupliquer que sur des sha256 relus, jamais sur un hash annoncé. */
                verified_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorePlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_store_summary_get: {
        parameters: {
            query?: {
                /** @description Seuil du poste « variants jamais utilisés ». */
                unused_after_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tiering_store_tiering_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TieringResponse"];
                };
            };
        };
    };
    deposer_fichier_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_deposer_fichier_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
