/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Où l'on est, et sur quel dépôt */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Le serveur répond-il */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registry/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contrats de capacité
         * @description Les contrats, avec ce que le parc en fait aujourd'hui.
         *
         *     C'est la source du formulaire de l'Atelier : `input` est rendu tel quel par
         *     RJSF, `output_media_types` choisit le visualiseur. `ready_variants` évite le
         *     piège d'un écran qui propose une capacité déclarée mais dont aucun variant
         *     n'est téléchargé.
         */
        get: operations["capabilities_registry_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registry/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Manifestes du parc */
        get: operations["models_registry_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime/admission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ce que coûterait ce job
         * @description Chiffre un job envisagé : pic attendu, évictions, marge — sans rien charger.
         *
         *     C'est une lecture malgré le verbe : rien n'est écrit, rien n'est chargé, et
         *     deux appels identiques donnent la même réponse. `POST` parce que la question
         *     porte une entrée complète, que l'on n'écrit pas dans une chaîne de requête.
         */
        post: operations["admission_runtime_admission_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime/residents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Modèles résidents et budget */
        get: operations["residents_runtime_residents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Occupation du parc */
        get: operations["summary_store_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdmissionOut */
        AdmissionOut: {
            /** Admitted */
            admitted: boolean;
            /**
             * Already Resident
             * @default false
             */
            already_resident: boolean;
            /** Blockers */
            blockers?: string[];
            /** Evict */
            evict?: string[];
            /**
             * Headroom Bytes
             * @default 0
             */
            headroom_bytes: number;
            /**
             * Measure Mode
             * @default false
             */
            measure_mode: boolean;
            /**
             * Peak Bytes
             * @description Pic attendu pour cette entrée, pas seulement pour ce variant.
             */
            peak_bytes?: number | null;
            /**
             * Peak Note
             * @description Dit quand le pic est extrapolé hors de l'intervalle mesuré.
             */
            peak_note?: string | null;
            /** Reason */
            reason: string;
            /** Ref */
            ref: string;
        };
        /** AdmissionRequest */
        AdmissionRequest: {
            /**
             * Input
             * @description Entrée envisagée, déjà typée. Elle sert au pic attendu quand le profil déclare une pente : trente secondes de musique coûtent le double de quinze.
             */
            input?: {
                [key: string]: unknown;
            };
            /**
             * Ref
             * @description « model@variant », ou « model » quand le choix est évident.
             */
            ref: string;
            /** Seed */
            seed?: number | null;
        };
        /** AdmissionResponse */
        AdmissionResponse: {
            admission: components["schemas"]["AdmissionOut"];
            /** Blockers */
            blockers?: string[];
            /**
             * Input
             * @description Entrée complète, défauts du contrat et du variant résolus.
             */
            input?: {
                [key: string]: unknown;
            };
            /**
             * Input Errors
             * @description Ce que le contrat reproche à l'entrée. Non vide, aucun job ne partirait.
             */
            input_errors?: string[];
            /** Ready */
            ready: boolean;
            /** Ref */
            ref: string;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /** Capabilities */
            capabilities: components["schemas"]["CapabilityOut"][];
            /** Issues */
            issues?: components["schemas"]["IssueOut"][];
        };
        /** CapabilityOut */
        CapabilityOut: {
            /**
             * Composite
             * @default false
             */
            composite: boolean;
            /**
             * Defaults
             * @description Valeurs par défaut déclarées par le contrat.
             */
            defaults?: {
                [key: string]: unknown;
            };
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /**
             * Incumbent
             * @description Titulaire de la capacité, référence de toute confrontation A/B.
             */
            incumbent?: string | null;
            /**
             * Input
             * @description JSON Schema du formulaire. L'UI le rend tel quel.
             */
            input: {
                [key: string]: unknown;
            };
            /**
             * Models
             * @description Modèles du registre qui remplissent cette capacité.
             */
            models?: string[];
            /**
             * Output
             * @description JSON Schema de la sortie.
             */
            output: {
                [key: string]: unknown;
            };
            /**
             * Output Media Types
             * @description Sorties qui sont des fichiers → type de média, qui choisit le visualiseur.
             */
            output_media_types?: {
                [key: string]: string;
            };
            /**
             * Ready Variants
             * @description Variants exécutables en l'état. Vide avec des modèles présents veut dire que la capacité est déclarée mais pas encore utilisable.
             */
            ready_variants?: string[];
            /** Required */
            required?: string[];
            /** Steps */
            steps?: {
                [key: string]: unknown;
            }[];
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IssueOut */
        IssueOut: {
            /** File */
            file: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning";
        };
        /** LinksOut */
        LinksOut: {
            /** Code */
            code?: string | null;
            /** Homepage */
            homepage?: string | null;
            /** Paper */
            paper?: string | null;
        };
        /** ModelOut */
        ModelOut: {
            /** Capability */
            capability: string;
            /** Family */
            family?: string | null;
            /** Id */
            id: string;
            /** Incumbent */
            incumbent: boolean;
            /** License */
            license: string;
            /** License Class */
            license_class?: string | null;
            links?: components["schemas"]["LinksOut"] | null;
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
            /** Status */
            status: string;
            /** Variants */
            variants: components["schemas"]["VariantOut"][];
            /** Vendor */
            vendor?: string | null;
        };
        /** ModelsResponse */
        ModelsResponse: {
            /**
             * Issues
             * @description Constats du chargement du registre. Un manifeste invalide n'est pas servi.
             */
            issues?: components["schemas"]["IssueOut"][];
            /** Models */
            models: components["schemas"]["ModelOut"][];
        };
        /** PeakScalingOut */
        PeakScalingOut: {
            /** Base Bytes */
            base_bytes: number;
            /** Bytes Per Unit */
            bytes_per_unit: number;
            /** Measured Range */
            measured_range: number[];
            /** Parameter */
            parameter: string;
            /** R Squared */
            r_squared?: number | null;
        };
        /** PolicyOut */
        PolicyOut: {
            /** Budget Bytes */
            budget_bytes: number;
            /** Heavy Threshold Bytes */
            heavy_threshold_bytes: number;
            /** Max Heavy Resident */
            max_heavy_resident: number;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Disk Bytes */
            disk_bytes: number;
            /** Harness Version */
            harness_version?: string | null;
            /** Latency Ms P50 */
            latency_ms_p50?: number | null;
            /**
             * Measured At
             * Format: date
             */
            measured_at: string;
            /** Measured On */
            measured_on: string;
            peak_scaling?: components["schemas"]["PeakScalingOut"] | null;
            /** Peak Unified Memory Bytes */
            peak_unified_memory_bytes: number;
            /** Rtf */
            rtf?: number | null;
            /** Throughput */
            throughput?: string | null;
            /** Warmup Ms */
            warmup_ms?: number | null;
        };
        /** ResidentOut */
        ResidentOut: {
            /** Busy */
            busy: boolean;
            /** Busy By */
            busy_by: number;
            /** Busy Since */
            busy_since: number;
            /** Env */
            env: string;
            /** Heavy */
            heavy: boolean;
            /** Last Used */
            last_used: number;
            /** Loaded At */
            loaded_at: string;
            /** Log */
            log: string;
            /**
             * Options
             * @description Ce que le worker a annoncé au chargement — voix, langues, versions.
             */
            options?: {
                [key: string]: unknown;
            };
            /** Peak Bytes */
            peak_bytes: number;
            /** Pid */
            pid: number;
            /** Pinned */
            pinned: boolean;
            /** Ref */
            ref: string;
            /** Runtime */
            runtime: string;
            /** Socket */
            socket: string;
            /** Warmup Ms */
            warmup_ms: number;
        };
        /** ResidentsResponse */
        ResidentsResponse: {
            admission?: components["schemas"]["AdmissionOut"] | null;
            /** Budget Bytes */
            budget_bytes: number;
            /**
             * Budget Measured
             * @description Le budget vient de Metal, et non d'une règle de trois sur la mémoire physique.
             */
            budget_measured: boolean;
            /** Budget Source */
            budget_source: string;
            /** Free Bytes */
            free_bytes: number;
            policy: components["schemas"]["PolicyOut"];
            /** Residents */
            residents: components["schemas"]["ResidentOut"][];
            /** Stale */
            stale?: components["schemas"]["StaleWorkerOut"][];
            /** Used Bytes */
            used_bytes: number;
        };
        /** SourceOut */
        SourceOut: {
            /** Allow Patterns */
            allow_patterns?: string[] | null;
            /** Kind */
            kind: string;
            /** Path */
            path?: string | null;
            /** Repo */
            repo?: string | null;
            /** Revision */
            revision?: string | null;
            /** Url */
            url?: string | null;
        };
        /**
         * StaleWorkerOut
         * @description Une entrée du registre des résidents qui ne correspond plus à un worker joignable.
         *
         *     Distinguer les deux cas est ce qui compte : un processus mort ne laisse
         *     qu'une ligne à balayer, un processus vivant dont le socket a disparu retient
         *     toujours ses gigaoctets et n'est plus comptable dans le budget.
         */
        StaleWorkerOut: {
            /** Holds Memory */
            holds_memory: boolean;
            /** Pid */
            pid: number;
            /** Ref */
            ref: string;
            /** Socket */
            socket: string;
        };
        /** StoreSummaryResponse */
        StoreSummaryResponse: {
            /**
             * Figures
             * @description Les trois chiffres et leur détail, tels que `ecurie_store.figures` les calcule. `null` — et non zéro — tant qu'aucun scan n'a eu lieu : un parc jamais regardé n'est pas un parc vide.
             */
            figures?: {
                [key: string]: unknown;
            } | null;
            /**
             * Hint
             * @description Ce qu'il faut faire quand la réponse est incomplète.
             */
            hint?: string | null;
            /** Last Scan At */
            last_scan_at?: string | null;
            /** Scanned */
            scanned: boolean;
            /**
             * Stale
             * @description Un plan a été appliqué depuis le dernier scan : ces chiffres sont périmés.
             * @default false
             */
            stale: boolean;
            telemetry?: components["schemas"]["TelemetryOut"] | null;
        };
        /** TelemetryOut */
        TelemetryOut: {
            /**
             * Conclusive
             * @description La télémétrie observe-t-elle depuis assez longtemps pour conclure ?
             */
            conclusive: boolean;
            /** First Run At */
            first_run_at?: string | null;
            /** Unused After Days */
            unused_after_days: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VariantOut */
        VariantOut: {
            /**
             * Blockers
             * @description Ce qui manque, chaque cause portant la commande qui la répare.
             */
            blockers?: string[];
            /** Caveats */
            caveats?: string[] | null;
            /** Defaults */
            defaults?: {
                [key: string]: unknown;
            } | null;
            /** Entrypoint */
            entrypoint?: string | null;
            /**
             * Env
             * @description Environnement isolé sous runtimes/, runtime par défaut.
             */
            env: string;
            /**
             * Heavy
             * @description Pic au-dessus de heavy_threshold_bytes : ce variant ne cohabitera avec aucun autre lourd. Inconnu sans profil mesuré.
             */
            heavy?: boolean | null;
            /** Id */
            id: string;
            /** Options */
            options?: {
                [key: string]: unknown;
            } | null;
            profile?: components["schemas"]["ProfileOut"] | null;
            /** Quantization */
            quantization?: string | null;
            /**
             * Ready
             * @description Exécutable en l'état : poids, environnement et profil.
             */
            ready: boolean;
            /**
             * Ref
             * @description « model@variant » — l'identifiant qu'attendent run et bench.
             */
            ref: string;
            /** Runtime */
            runtime: string;
            source: components["schemas"]["SourceOut"];
            /**
             * Tier
             * @description Présence déclarée au manifeste : hot, cold ou absent.
             */
            tier: string;
            /**
             * Weights Path
             * @description Chemin local des poids, quand ils sont là.
             */
            weights_path?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    capabilities_registry_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    models_registry_models_get: {
        parameters: {
            query?: {
                /** @description Ne rendre que les modèles de cette capacité. */
                capability?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admission_runtime_admission_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdmissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdmissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    residents_runtime_residents_get: {
        parameters: {
            query?: {
                /** @description Simuler l'admission de ce variant, sans rien charger ni décharger. */
                for?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_store_summary_get: {
        parameters: {
            query?: {
                /** @description Seuil du poste « variants jamais utilisés ». */
                unused_after_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
